name: Android CI - Prod

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - run: chmod +x ./gradlew

      - name: Extract versionName
        id: version
        run: |
          VERSION_NAME=$(grep versionName app/build.gradle | head -1 | awk -F'"' '{ print $2 }')
          echo "version_name=$VERSION_NAME" >> $GITHUB_OUTPUT

      - name: Build Prod APK
        run: ./gradlew assembleProdRelease

      - name: Create Git Tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag v${{ steps.version.outputs.version_name }} || true
          git push origin v${{ steps.version.outputs.version_name }} || true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.version_name }}
          name: "Prod Release v${{ steps.version.outputs.version_name }}"
          files: app/build/outputs/apk/prod/release/*.apk
